import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "../app/components/navbar/Nav.jsx"; // Import your custom CSS for the navbar
import Faq from "./components/faq/Faq";
import Foot from "./components/Foot";
import ScrollTop from "./components/ScrollTop";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Stacking | Crea tu Stack",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body
        className={`${inter.className} antialiased`}
        cz-shortcut-listen="false"
      >
        <Nav />
        {children}

        <Faq />
        <ScrollTop />
        <Foot />
      </body>
    </html>
  );
}
